title: Dinushka Shonal Geekiyanage
logo: /assets/profile.png
description: Hospitality Information Technology Manager - NOC Level 3 Engineer
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
